spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 600000
      maximum-pool-size: 15
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

# mybatis configuration: scan mapper.xml files
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 输出 mybatis SQL 语句，调试时打开，上线关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

