# port
server:
  port: 7666
  servlet:
    context-path: /v1.0/api/
    session:
      timeout: 3600s

# datasource
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: 192.168.2.2
    port: 6379
    password: Root123!@$
    timeout: 0
    database: 3
    jedis:
      pool:
        max-active: 3000
        max-idle: 8
        max-wait: -1
        min-idle: 0
  datasource:
    url: jdbc:postgresql://192.168.2.2:5432/sishi
    username: postgres
    password: Root123!@$
    driver-class-name: org.postgresql.Driver
#    url: jdbc:mysql://localhost:3306/localdb
#    username: root
#    password: root123
#    driver-class-name: com.mysql.jdbc.Driver

myconfig:
  nginx:
    host: 192.168.2.2
    port: 8088
    httpHead: http://${myconfig.nginx.host}:${myconfig.nginx.port}
    winRoot: F:/SSNginx/webresource
    linuxRoot: /home/webresource
    picPath: /sishi/picture/
    audioPath: /sishi/audio/
    videoPath: /sishi/video/