# port
server:
  port: 8080
  servlet:
    context-path: /v1.0/api/
    session:
      timeout: 3600s

# datasource
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: 192.168.137.1
    port: 6379
    password: Root123!@$
    timeout: 0
    database: 3
    jedis:
      pool:
        max-active: 3000
        max-idle: 8
        max-wait: -1
        min-idle: 0
  datasource:
    url: jdbc:postgresql://192.168.137.1:5432/sishi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    username: 2643094929@qq.com
    password: oswgfnpksbjiebhf
    port: 587
    default-encoding: utf-8
    properties:
      mail:
        stmp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
#            fallback: false

myconfig:
  # Nginx
  nginx:
    host: 47.100.24.69
    port: 80
    httpHead: http://${myconfig.nginx.host}:${myconfig.nginx.port}/media/
    winRoot: F:/0temp/Nginx/webResource/
    linuxRoot: /home/sishi/static/
    picPath: picture/
    audioPath: audio/
    videoPath: video/
