# port
server:
  port: 8080
  servlet:
    context-path: /v1.0/api/
    session:
      timeout: 3600s

# datasource
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: 47.100.24.69
    port: 6379
    password: Root123!@$
    timeout: 0
    database: 3
    jedis:
      pool:
        max-active: 3000
        max-idle: 8
        max-wait: -1
        min-idle: 0
  datasource:
    url: jdbc:postgresql://47.100.24.69:5432/sishi
    username: postgres
    password: Root123!@$
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    username: 2643094929@qq.com
    password: oswgfnpksbjiebhf
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8

myconfig:
  # Nginx
  nginx:
    host: 47.100.24.69
    port: 80
    httpHead: http://${myconfig.nginx.host}:${myconfig.nginx.port}/media/
    winRoot: F:/SSNginx/webresource/
    linuxRoot: /home/sishi/static/
    picPath: picture/
    audioPath: audio/
    videoPath: video/
